export interface ExpertiseItem {
  title: string;
  description: string;
  icon: string;
}

export interface TimelineEntry {
  id: string;
  company: string;
  role: string;
  current?: boolean;
  description: string;
  icon: string;
}

export interface SuccessStory {
  id: string;
  name: string;
  category: string;
  summary: string;
  achievements?: string[];
  contributions: string[];
  stat?: { value: string; label: string };
  icon: string;
  /** Key into `media-manifest.json` -> `cards`. Generated by `npm run media`
   *  from the matching file in `src/Assets`. */
  imageKey: string;
}

export interface StatItem {
  value: string;
  label: string;
}

export interface Testimonial {
  name: string;
  role: string;
  text: string;
}
